### ISSUE TITLE
Incorrect header height sizing on 16:9 resolution

### ISSUE THREAD

**Issue by Cj1m** [vesoapp/veso-web#180]
**Describe The Bug**
When the browser window's width is expanded too wide, the header height is displayed incorrectly:
https://ibb.co/SJbWYVG

**Steps To Reproduce**
Open veso web fullscreen on browser at resolution (16:9) 2560 x 1440

**Expected Behavior**
Header should look more like this, so that the veso logo is not obscured:
https://ibb.co/WnpdCZ1

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Tested in Firefox, Chrome
 - Veso Version: 10.8.4

**Comment by dannymichel** [comment]
Will fix this soon.

**Comment by dannymichel** [comment]
Fixed in https://github.com/vesoapp/veso-web/pull/181
